### PR TITLE
Added tool to normalize intensities of an image.

### PR DESCRIPTION
**Pull request by carokrug**

### CODE REVIEW

**Review by bgruening — COMMENTED** [review]
@carokrug the test file is too big. Can you try to reduce the test file size to be minimal?

**Comment by carokrug** [comment]
Yes sure, I didn't know that, sorry! I'll also check the style regarding the flake8 again.

**Comment by bgruening** [comment]
@qgao-hd Oo did I miss here something?

**Comment by qgao-hd** [comment]
@bgruening No, you didn't miss anything. My colleague simply did a trial integration of new tools into Galaxy before I left the BMCV group.

**Pull request closed without merging**
