### PR TITLE
fixes required superdsm version to 0.1.2=*_1

### PR DESCRIPTION
**Pull request by kostrykin**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

---

an attempt of solving https://github.com/usegalaxy-eu/usegalaxy-eu-tools/issues/599

### CODE REVIEW

**Comment by bgruening** [comment]
Oh damn, is conda installing an older version?

**Comment by kostrykin** [comment]
@bgruening No, it's not installing any version at all. It's just a wild guess that fixing the build maybe will make it install it.

**Comment by bgruening** [comment]
Oh I now understand... https://anaconda.org/anaconda/posix_ipc is only available in the anaconda channel but not in conda-forge. That seems to be the reason. To fix that properly I think we would need to create the recipe in conda-forge.

For the meantime, I have fixed the environment on EU by manually enabling the anaconda channel for this repo.


Can you try it on EU maybe?

**Comment by kostrykin** [comment]
Thank you very much, @bgruening! Indeed, this was the reason of the issue. I just tested the tool on EU and it works now.

> To fix that properly I think we would need to create the recipe in conda-forge.

I think I will rather make `posix_ipc` an optional requirement for the tool (by default, the use of `posix_ipc` is deactivated anyways, so this seems the cleaner solution).

>  https://anaconda.org/anaconda/posix_ipc is only available in the anaconda channel but not in conda-forge. That seems to be the reason.

But this means that conda-forge is enabled the CI of the _galaxy-image-analysis_ repo, right? To rule out similar issues in the future, maybe we should disable it?

**Comment by bgruening** [comment]
Yes somewhere the default/anaconda channel gets still activated, I need to find out where this happens.

Thanks for trying!

**Pull request closed without merging**
