### PR TITLE
fixes flake8 of 2d_filter_segmentation_by_features

### PR DESCRIPTION
**Pull request by kostrykin**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/galaxyproject/tools-iuc/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the tools-iuc repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)

### CODE REVIEW

**Comment by kostrykin** [comment]
From [this](https://github.com/BMCV/galaxy-image-analysis/actions/runs/5276757799/jobs/9544072761#step:8:564) it seems that the build is failing due to
```
+ read -r -a TOOL_GROUP
+ '[' '!' -s tool_list_chunk.txt ']'
+ planemo merge_test_reports 'json_output/*.json' tool_test_output.json
Total reclaimed space: 3.612GB
Traceback (most recent call last):
  File "/opt/hostedtoolcache/Python/3.7.17/x64/bin/planemo", line 5, in <module>
    from planemo.cli import planemo
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/planemo/cli.py", line 24, in <module>
    from planemo.galaxy import profiles
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/planemo/galaxy/__init__.py", line 4, in <module>
    from .config import galaxy_config
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/planemo/galaxy/config.py", line 38, in <module>
    from planemo.galaxy.workflows import remote_runnable_to_workflow_id
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/planemo/galaxy/workflows.py", line 14, in <module>
    from ephemeris import (
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/ephemeris/generate_tool_list_from_ga_workflow_files.py", line 13, in <module>
    from .shed_tools import InstallRepoDict
  File "/opt/hostedtoolcache/Python/3.7.17/x64/lib/python3.7/site-packages/ephemeris/shed_tools.py", line 62, in <module>
    from typing_extensions import (
ImportError: cannot import name 'NamedTuple' from 'typing_extensions'
```
which seems unrelated to the tool.

**Comment by bgruening** [comment]
Thanks @kostrykin!
This looks good to me, but do we need to ship this to the ToolShed? It has not features or bug fixes, does it?
I would merge it and not push to the TS, if you agree.

**Comment by kostrykin** [comment]
> Thanks @kostrykin!
> This looks good to me, but do we need to ship this to the ToolShed? It has not features or bug fixes, does it?
> I would merge it and not push to the TS, if you agree.

Nope, no new features or bug fixes. I was searching for a bug, but couldn't reproduce it locally. Still, while searching it, I fixed the flake8. Please continue merging it if you think it is appropriate!

Still, I was wondering, why the Status checks were failing in the first place. It initially failed as described [here](https://github.com/BMCV/galaxy-image-analysis/pull/54#issuecomment-1592733427). Then, I noticed that the action for PRs has been [changed recently](https://github.com/BMCV/galaxy-image-analysis/commit/f3e217b89e62200843d5cabb0ac111183a88a019#diff-1eb4e5fd5611777d4e597ef299a1cb5ba8050c28a2dabbd4fbc56205d69e5dda). So I created another branch (pr-fix), on which I reverted the changed made back then, and created [another PR](https://github.com/BMCV/galaxy-image-analysis/pull/56) from `kostrykin:2d_filter_segmentation_by_features` to `BMCV:pr-fix`. Subsequently, _both_ PRs failed the Status checks, but when looking at the [workflow runs](https://github.com/BMCV/galaxy-image-analysis/actions), I saw that the workflow run for _this_ PR here was successful and only failed for the other PR. Isn't this weird, since I neither made any changes to `kostrykin:2d_filter_segmentation_by_features` nor to `BMCV:master`? It gets even weirder: I explicitly triggered the workflow run for _this_ PR only, and doing that, GitHub reported that the Status checks passed for _both_ PRs.

**Comment by bgruening** [comment]
Let me know if there is anything to do ...

**Pull request closed without merging**
