### PR TITLE
Update ip_imageinfo, update CI to release_24.1

### PR DESCRIPTION
**Pull request by bernt-matthias**
If admins set `_JAVA_OPTIONS` the stderr will contain `Picked up _JAVA_OPTIONS: -Xmx6g -Xms256m`. For legacy tools (without profile) any text in the stderr will make the tool fail.

---

**FOR THE CONTRIBUTOR — Please fill out if applicable**

Please make sure you have read the [CONTRIBUTING.md](https://github.com/BMCV/galaxy-image-analysis/blob/master/CONTRIBUTING.md) document (last updated: 2024/04/23).

* [ ] License permits unrestricted use (educational + commercial).

If this PR adds or updates a tool or tool collection:

* [ ] This PR adds a new tool or tool collection.
* [ ] This PR updates an existing tool or tool collection.
* [ ] Tools added/updated by this PR comply with the [Naming and Annotation Conventions for Tools in the Image Community in Galaxy](https://doi.org/10.37044/osf.io/w8dsz) (or explain why they do not).

### CODE REVIEW

**Review by kostrykin — COMMENTED** [review]
Thanks!

> File "/opt/hostedtoolcache/Python/3.11.9/x64/lib/python3.11/site-packages/planemo/lint.py", line 45, in build_lint_args
    linters = Linter.list_linters()
              ^^^^^^^^^^^^^^^^^^^
AttributeError: type object 'Linter' has no attribute 'list_linters'. Did you mean: 'list_listers'?

https://github.com/BMCV/galaxy-image-analysis/actions/runs/9888925228/job/27314122230?pr=124#step:8:437

Any idea why this is? Looks like a typo in planemo/lint.py?

**Comment by bernt-matthias** [comment]
See https://github.com/galaxyproject/galaxy/blob/a7fb5711431df5995b65330b5c99ac0503e8eec9/lib/galaxy/tool_util/lint.py#L115C68-L115C72 https://github.com/galaxyproject/galaxy/pull/18339.

Bottom line is that I fixed a typo. But we already had code (planemo) using the code with the typo. The proper fix would be to backport https://github.com/galaxyproject/galaxy/pull/18339 and to release new packages for 23.2 .. but I'm not sure if it's worth the effort. 

The workaround in to use the most recent branches. Problem is that currently the pip cache is not updated (probably only happens after the changes to the workflows are merged).

**Comment by kostrykin** [comment]
> The workaround in to use the most recent branches. Problem is that currently the pip cache is not updated (probably only happens after the changes to the workflows are merged).

To test this, I have merged the changes into a fork: https://github.com/kostrykin/galaxy-image-analysis/pull/6 and then I triggered the CI by bumping a tool version: https://github.com/kostrykin/galaxy-image-analysis/pull/7 This still yields the same error. So I guess merging the changes to the workflows is not sufficient?

**Comment by bernt-matthias** [comment]
I see. There was more to remove :)

**Comment by kostrykin** [comment]
Right, I also had forgotten about those. Thanks!

FTR: 6bc8575d700f6ec7a194566a335c4879385f12b4 reverts the temporary changes introduced in #117.

**Pull request merged**
