### PR TITLE
Update SuperDSM to 0.2.0

### PR DESCRIPTION
**Pull request by kostrykin**
FOR CONTRIBUTOR:
* [x] - I have read the [CONTRIBUTING.md](https://github.com/BMCV/galaxy-image-analysis/blob/master/CONTRIBUTING.md) document and this tool is appropriate for the galaxy-image-analysis repo.
* [x] - License permits unrestricted use (educational + commercial)
* [ ] - This PR adds a new tool or tool collection
* [x] - This PR updates an existing tool or tool collection
* [ ] - This PR does something else (explain below)
* [x] - Tools added/updated by this PR (if any) comply with the [Naming and Annotation Conventions for Tools in the Image Community in Galaxy](https://github.com/elixir-europe/biohackathon-projects-2023/blob/main/16/conventions.md) (or please explain why they do not)

### CODE REVIEW

**Comment by kostrykin** [comment]
Prior to 19f66e3 the tests did not fail, although the output data was wrong:
```xml
<output name="cfg" value="cfg.tsv" ftype="tsv" compare="sim_size" />
```
The test passed, although the size of the output data and test data differed by >50%:
```
$ ls -al test-data/cfg.tsv
-rw-rw-r-- 1 void void 2636 Nov 16 13:11 test-data/cfg.tsv
$ ls -al /tmp/tmps7vy1dlv/job_working_directory/000/4/working/cfg.tsv
-rw-r--r-- 1 void void 1156 Feb  7 13:38 /tmp/tmps7vy1dlv/job_working_directory/000/4/working/cfg.tsv
```
This is because, by default, the threshold for comparison is much larger than the file itself,
> `delta`: If compare is set to sim_size, this is the maximum allowed absolute size difference (in bytes) between the data set that is generated in the test and the file in test-data/ that is referenced by the file attribute. Default value is 10000 bytes. Can be combined with delta_frac.
> `delta_frac`: If compare is set to sim_size, this is the maximum allowed relative size difference between the data set that is generated in the test and the file in test-data/ that is referenced by the file attribute. A value of 0.1 means that the file that is generated in the test can differ by at most 10% of the file in test-data. The default is not to check for relative size difference. Can be combined with delta.

as stated in the documentation ([link](https://docs.galaxyproject.org/en/latest/dev/schema.html#tool-tests-test-output)).

@bgruening I think this quite dangerous, that a that large default threshold is used for `delta`. At least, shouldn't it be checked by the linter, whether the set `delta` is reasonable in relation to the actual test file?

**Comment by bgruening** [comment]
> @bgruening I think this quite dangerous, that a that large default threshold is used for delta. At least, shouldn't it be checked by the linter, whether the set delta is reasonable in relation to the actual test file?

Probably, but using a delta and sizes are dangerous on their own.
Q to the imaging expert, is there a way to "diff an image" that we can use in Galaxy tests?

**Comment by kostrykin** [comment]
> Q to the imaging expert, is there a way to "diff an image" that we can use in Galaxy tests?

@bgruening There are different metrics for image comparison, and depending on the type of image, one might be better suited than the other: You want to compare _(i)_ intensity images differently than you compare _(ii)_ binary masks or label maps.

For _(i)_ intensity images, using the Frobenius norm, the Root Mean Square Error (RMS), or the Mean Square Error (MSE) are the most widely established methods, which also are very simple to implement (one-liners using numpy). However, establishing a threshold for these three can be tricky in practice. Thus, I rather prefer to
1. count the number of differing pixels, subject to some absolute threshold (typically 1/256 for 8bit images)
2. determine the RMS of only the differing pixels and compare to some threshold.

In my experience, this is more robust than using the RMS directly, because it is less sensitive to differing image sizes (and differing number of color channels).

For _(ii)_ binary masks and label maps, I wrote a whole Python package for exactly this purpose ([segmetrics](https://github.com/BMCV/segmetrics.py)). People have been thinking about what the most elegant way of comparing that type of images might be for decades, which indicates, that there probably are no hard and fast rules. The most *simple* method for *binary masks* is too consider the Dice coefficient, which, again, is a one-liner using numpy. But for *label maps*, things get more tricky. In my opinion, using the Dice coefficient in conjunction with the SEG measure is most expressive, as I had explained in a [paper](http://evoid.de/kostrykin2023-accepted-manuscript.pdf) of mine:

> Notably, Dice and Rand are sensitive to false-positive detections, but invariant to falsely split/merged objects. On the other hand, SEG is sensitive to falsely split/merged objects and false-negative detections (but invariant to false-positive detections). Overall, SEG is the most comprehensive and best suited measure for region-based segmentation performance since it incorporates both detection and object-based segmentation performance.

In some applications, however, contour-based measures are better suited than region-based measures, for example, when it comes to comparing binary images of line-like structures. In that case, there might be hardly any overlap between the lines within two images, meaning that region-based measures will report that the images are very dissimilar, although there is only a small offset between the lines. For comparison of such images, contour-based measures like the Hausdorff-distance (HSD) or the normalized sum of distances (NSD) are better suited.

All of these are implemented in segmetrics, btw :)

**Comment by bgruening** [comment]
Always good to ask an expert :)

I'm asking because this entire `assert` infrastructure in Galaxy is also plugin based.
See here for example: https://github.com/galaxyproject/galaxy/tree/dev/lib/galaxy/tool_util/verify/asserts

Example PR: https://github.com/galaxyproject/galaxy/pull/7301

The thing is the dependencies should be minimal that we need to add to Galaxy.

**Comment by kostrykin** [comment]
> Always good to ask an expert :)
> 
> I'm asking because this entire `assert` infrastructure in Galaxy is also plugin based. See here for example: https://github.com/galaxyproject/galaxy/tree/dev/lib/galaxy/tool_util/verify/asserts
> 
> Example PR: [galaxyproject/galaxy#7301](https://github.com/galaxyproject/galaxy/pull/7301)
> 
> The thing is the dependencies should be minimal that we need to add to Galaxy.

Ah, thanks for pointing out!

Sounds like a new project for the upcoming [Hackathon Image Analysis in Galaxy](https://galaxyproject.org/events/2024-02-26-hackathon-image-analysis-in-galaxy/) has just emerged ;)

**Comment by bgruening** [comment]
lol :)

**Pull request merged**
