### PR TITLE
added new tool: spot detection in 2D image sequence

### PR DESCRIPTION
**Pull request by qgao-hd**

### CODE REVIEW

**Comment by qgao-hd** [comment]
@bgruening Hi Björn, could you please take a look why the auto check did not start (I saw the message "Workflow runs completed with no jobs")? I did something wrong? 
Thanks!

**Comment by bgruening** [comment]
Travis is really out of date and changed their service. I added GitHub based testing now. Hope that works.

**Comment by bgruening** [comment]
The downside or upside is that we linting your python code now as well :) Can you fix the flake8 issues?

**Comment by qgao-hd** [comment]
> The downside or upside is that we linting your python code now as well :) Can you fix the flake8 issues?

Thanks for prompt response! I am not familiar with flake8. Do I simply need to fix all listed issues of coding standards (for example, missing whitespaces)?

**Comment by bgruening** [comment]
> > The downside or upside is that we linting your python code now as well :) Can you fix the flake8 issues?
> 
> Thanks for prompt response! I am not familiar with flake8. Do I simply need to fix all listed issues of coding standards (for example, missing whitespaces)?

yes, you can also `pip install flake8` and use that for linting your code locally. Your editor has probably a flake8 plugin as well.

**Comment by qgao-hd** [comment]
> The downside or upside is that we linting your python code now as well :) Can you fix the flake8 issues?

flake8 issues fixed. 

Now the check stops at "Check outputs".

**Comment by bgruening** [comment]
Go to this page https://github.com/BMCV/galaxy-image-analysis/pull/25/checks?check_run_id=3122707432

image

Download the "All tool test results" and you will see this error:

image

**Comment by qgao-hd** [comment]
> Go to this page https://github.com/BMCV/galaxy-image-analysis/pull/25/checks?check_run_id=3122707432
> 
> Download the "All tool test results" and you will see this error:
> 

I did not notice that I can download the results. All problems solved! Thanks! 

I will add more new tools in the following days.

**Comment by bgruening** [comment]
> I did not notice that I can download the results. All problems solved! Thanks!

No worries, its a new feature :)

> I will add more new tools in the following days.

That is pretty cool! Are you using them? Should we get those all on the European Galaxy server?

**Comment by qgao-hd** [comment]
> 
> That is pretty cool! Are you using them? Should we get those all on the European Galaxy server?

Yes, we need to get these tools on usegalaxy.eu. (I will edit the imaging.yaml file and create a PR soon.) We and our biological partners will use the tools and develop some new workflows. 

Shall I worry about the failure of Slash Command Dispatch before merging the this PR?

BTW, since there have been a number of imaging tools, shall we (or is it possible to) sort these tools on usegalaxy.eu (or in "imaging.yaml") in an alphabetical order for easy access?

**Comment by bgruening** [comment]
> BTW, since there have been a number of imaging tools, shall we (or is it possible to) sort these tools on usegalaxy.eu (or in "imaging.yaml") in an alphabetical order for easy access?

Yes, I could sort them with your preferred order.

**Review by bgruening — APPROVED** [review]

**Comment by bgruening** [comment]
I need to set some github credentials, but I'm not admin here? Are you admin in this repo?

**Comment by qgao-hd** [comment]
> I need to set some github credentials, but I'm not admin here? Are you admin in this repo?

Yes, I am. I just added you as the maintainer. Could you try it again?

**Comment by bgruening** [comment]
I feel the power ;)

**Comment by bgruening** [comment]
Mh, but its not enough, I can not see the "secrets" tab in the settings :(

**Comment by qgao-hd** [comment]
> Mh, but its not enough, I can not see the "secrets" tab in the settings :(

OK, now you must be able to do anything you want, ;) Is it related to Github Actions?

**Comment by bgruening** [comment]
Yes, the GitHub Actions are now loading the tools automatically to the Galaxy Tool Shed and I needed to put the API key as "secret" into the repo. You can remove my privileges now again if you like.

Thanks @qgao-hd!

**Pull request merged**
