### PR TITLE
fixed problems with projective transformation of ROIs

### PR DESCRIPTION
**Pull request by qgao-hd**
Fixed problems with projective transformation of ROIs and updated the tool “projective_transformation_point” (both the python file and corresponding xml file).

### CODE REVIEW

**Comment by bgruening** [comment]
@qgao-hd thanks! I'm a little bit puzzeled why the travis tests are not running. Do you have admin access and can look at the settings?

**Comment by qgao-hd** [comment]
@bgruening I do not have the admin access. Sorry, I am new to Galaxy Image Analysis and have no idea about the travis tests. What is that?

**Comment by bgruening** [comment]
Travis is a Continues Integration system. So everything gets tested in this repo. Unfortunately, the test do not run :(

@ThomasWollmann are you still around? :)

**Comment by ThomasWollmann** [comment]
> Travis is a Continues Integration system. So everything gets tested in this repo. Unfortunately, the test do not run :(
> 
> @ThomasWollmann are you still around? :)

I'm around. Will take care if Travis soon.

**Comment by ThomasWollmann** [comment]
will have to migrate to github actions

**Comment by ThomasWollmann** [comment]
Travis does not run on external repositories. @qgao-hd added you to the BMCV organisation so that you can directly push to the repository.

**Comment by qgao-hd** [comment]
@ThomasWollmann I am still not able to directly push to the repository: "remote: Permission to BMCV/galaxy-image-analysis.git denied to qgao-hd." Could you please check it again? Thanks.

**Comment by bgruening** [comment]
@qgao-hd for the time being you can create a PR I thnink.

**Pull request merged**
